language: ruby
rvm:
  - 2.1.0
install: gem install jekyll html-proofer
script: jekyll build && htmlproofer ./_site --only-4xx  --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
after_success: s3_website push
