language: ruby
rvm:
  - 2.1.1
install: gem install jekyll && gem install s3_website
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx  --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
after_success: s3_website push
