highlighter: pygments
url: https://www.tiernanotoole.ie
title: "Tiernan's Comms Closet"
lsi: false

paginate_path: "/page:num/"
paginate: 5

plugins:
  -  jekyll-paginate
  -  jekyll-seo-tag
  -  jekyll-archives
  -  jekyll-redirect-from  
algolia:
    vars: ["title", "excerpt", "date", "url", "categories", "tags"]

jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

prose:
  rooturl: '_posts'

description: "homepage of Tiernan OToole, Geek, photographer, GeekPhotographer, and lazy git."

twitter:
  username: tiernano

social:
  name: Tiernan OToole
  links:
    https://twitter.com/tiernano
    

logo: images/f13a7d94b648a3a15655f0ec1dc3284e.jpeg

seo:
  name: Tiernan OToole's Blog
  type: BlogPosting

author:
  twitter: tiernano

exclude: ["vendor",
        "_assets",
        "Gemfile",
        "Gemfile.lock",
        "gulpfile.js",
        "node_modules",
        "package.json"]
