highlighter: pygments
url: https://www.tiernanotoole.ie
lsi: false

paginate_path: "/page:num/"
paginate: 5

gems:
  -  jekyll-paginate

prose:
  rooturl: '_posts'

description: "homepage of Tiernan OToole, Geek, photographer, GeekPhotographer, and lazy git."
